### ISSUE TITLE
Organization not shown for profile

### ISSUE THREAD

**Issue by kristianmandrup** [narrowcast/hasdocs.com#28]
Hi,
I'm a member of https://github.com/smigit organization. When I signed up I approved access to organization but it is not shown on my profile page, only my personal repos. Is this a limitation with the free version or an error. We need a way to create documentation websites for our main repos, then link them together from a "documentation hub" repo.

Any help, advice etc. greatly appreciated. What are the billing plans if any?
I can see most of the code was done 2 years ago, but still in beta.
Please upgrade the documentation and step-by-step guide for both personal, organisation, private and public repos. Thanks :)

**Comment by kristianmandrup** [comment]
I looked into the code. I can see there is some quite complex security logic such as:


I can also see in setings/connections there is a github security token. Please document how to use it.
What can I see when I'm an owner vs not an owner etc. I assume hasdocs works (perhaps), but that I don't see the org. repos since I'm not an owner of the organization?

```
class ProjectManager(models.Manager):
    """Manager for returning various project sets."""

    def owned_by(self, account, user):
        """Returns the projects owned by given user or organization account."""
        queryset = Project.objects.filter(owner=account)
        if not user.is_authenticated():
            # Then only return public projects
            return queryset.filter(private=False)
        if account.is_organization():
            if user.is_owner(account):
                # Then return everything
                return queryset
            elif account.members.filter(pk=user.pk).exists():
                # Then return only the repos that user's teams have access to
                public_set = queryset.filter(private=False)
                member_set = queryset.filter(teams=user.team_set.all)
                return (public_set | member_set).distinct()
            else:
                return queryset.filter(private=False)
        else:
            if user.is_owner(account):
                # Then return everything
                return queryset
            else:
                # Then return only the repos that user is collaborating on
                public_set = queryset.filter(private=False)
                member_set = queryset.filter(collaborators=user)
                return (public_set | member_set).distinct()
```

**Comment by yoonchee** [comment]
Unfortunately, this was our side project long time ago and we can't provide any support for it. Please feel free to go ahead and send a pull request if you would like to.
